import Head from "next/head";
import Image, { StaticImageData } from "next/image";
import Link from "next/link";
import { Tab } from "@headlessui/react";
import { Tabs } from "@/models/Tabs";
import Masonry from "react-masonry-css";
import classNames from "classnames";
import ocean1 from "../../public/ocean-01.jpg";
import ocean2 from "../../public/ocean-02.jpg";
import ocean3 from "../../public/ocean-03.jpg";
import ocean4 from "../../public/ocean-04.jpg";
import ocean5 from "../../public/ocean-05.jpg";
import ocean6 from "../../public/ocean-06.jpg";

export default function Home() {
  const tabs: Tabs[] = [
    { key: "all", display: "All" },
    { key: "oceans", display: "Oceans" },
    { key: "forest", display: "Forest" },
  ];

  const images: StaticImageData[] = [
    ocean1,
    ocean4,
    ocean3,
    ocean2,
    ocean5,
    ocean6,
  ];
  return (
    <div className="Coming_Soon h-full bg-[url('/photography-bg.jpg')] bg-center bg-cover overflow-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="bg-stone-900 fixed top-0 w-full z-10 flex justify-between items-center h-[90px] px-10">
        <span className="uppercase text-lg font-medium">
          Photography Portfolio
        </span>
        <Link
          href="#"
          className="rounded-3xl bg-white text-stone-700 px-3 py-2 hover:bg-opacity-90"
        >
          Get in touch
        </Link>
      </header>
      <main className="pt-[110px]">
        <div className="flex flex-col items-center h-full">
          <Tab.Group>
            <Tab.List className="flex items-center gap-12">
              {tabs.map(({ key, display }) => (
                <Tab key={key} className="p-2 uppercase">
                  {({ selected }) => (
                    <span
                      className={classNames(
                        "uppercase text-lg",
                        selected ? "text-white" : "text-stone-600"
                      )}
                    >
                      {display}
                    </span>
                  )}
                </Tab>
              ))}
            </Tab.List>
            <Tab.Panels className="h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
              <Tab.Panel>
                <Masonry
                  breakpointCols={2}
                  className="flex gap-4"
                  columnClassName=""
                >
                  {images.map((image, index) => (
                    <Image
                      src={image}
                      alt={`image-${index}`}
                      className="my-4"
                    />
                  ))}
                </Masonry>
              </Tab.Panel>
              <Tab.Panel>Ocenas</Tab.Panel>
              <Tab.Panel>Forest</Tab.Panel>
            </Tab.Panels>
          </Tab.Group>
        </div>
      </main>
      <footer className="h-[90px] flex justify-center items-center uppercase text-lg font-medium">
        <p>Photography Portfolio</p>
      </footer>
    </div>
  );
}
